# Generated by Django 6.0.6 on 2026-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=999)),
                ('Descripcion', models.CharField(max_length=999)),
                ('icono', models.TextField(blank=True, null=True)),
                ('ruta', models.CharField(max_length=999)),
            ],
        ),
    ]
